const { Sequelize, DataTypes } = require('sequelize');

const sequelize = new Sequelize('gj', 'sa', '@Gaja2024', {
  host: '102.213.182.8',
  dialect: 'mssql',
  dialectOptions: { options: { encrypt: false, trustServerCertificate: true } },
});

const PayrollArchivedSalary = sequelize.define('PayrollArchivedSalary', {
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  year: { type: DataTypes.INTEGER, allowNull: false },
  month: { type: DataTypes.INTEGER, allowNull: false },
  id_emp: { type: DataTypes.BIGINT, allowNull: false },
  name: { type: DataTypes.STRING(120), allowNull: true },
  ps: { type: DataTypes.INTEGER, allowNull: true },
  base_salary_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  base_salary_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  food_days: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
  wd_food_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  wd_food_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  absence_days: { type: DataTypes.DECIMAL(9,2), allowNull: false, defaultValue: 0 },
  absence_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  absence_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  ph_days: { type: DataTypes.DECIMAL(9,2), allowNull: false, defaultValue: 0 },
  ph_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  ph_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  missing_minutes: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
  missing_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  missing_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  total_salary_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  total_salary_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  gold_bonus_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  gold_bonus_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  diamond_bonus_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  diamond_bonus_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_bonus1_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_bonus1_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_bonus1_acc: { type: DataTypes.STRING(11), allowNull: true },
  other_bonus2_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_bonus2_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_bonus2_acc: { type: DataTypes.STRING(11), allowNull: true },
  loan_debit_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  loan_debit_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  loan_credit_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  loan_credit_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_additions_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_additions_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_deductions_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  other_deductions_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  net_salary_lyd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  net_salary_usd: { type: DataTypes.DECIMAL(19,4), allowNull: false, defaultValue: 0 },
  // archive metadata
  closed_by: { type: DataTypes.INTEGER, allowNull: true },
  closed_at: { type: DataTypes.DATE, allowNull: true },
  gl_doc_no: { type: DataTypes.STRING(50), allowNull: true },
  locked: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },
}, {
  tableName: 'PayrollArchivedSalary',
  freezeTableName: true,
  timestamps: false,
});

module.exports = PayrollArchivedSalary;
